services:
  app:
    container_name: bap_dashboard
    image: fvckdecops/bap_dashboard
    restart: always
    # env_file:
    #   - .env
    ports:
      - 1337:1337
    volumes:
      - ./json:/json
    environment:
      - TZ=Asia/Jakarta