version: '3'
services:
  app:
    container_name: bap_dashboard
    image: fvckdecops/bap_dashboard
    restart: always
    ports:
      - 80:1337
      - 443:1337
    volumes:
      - ./json:/json
    environment:
      - TZ=Asia/Jakarta