name: Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Download required files"
        run:
          mkdir ~/bap-dashboard/json
          curl -o ~/bap-dashboard/json/_about.json https://gist.githubusercontent.com/fvckdecops/7b7b1889fe508a11e08c56813be2b07c/raw/06d43369ccbddda62da6eaf3292f432462e14e8b/_about.json
          curl -o ~/bap-dashboard/json/_experiences.json https://gist.githubusercontent.com/fvckdecops/e703aeaadfaf639990cc3c5325db87ad/raw/5a743d8571caf9cc1f82ae7245f8b1c3914d597e/_experiences.json
          curl -o ~/bap-dashboard/json/_projects.json https://gist.github.com/fvckdecops/bb258b8af50ba02ab10bd1852273467f/raw/beb27cd9fcfc539e4271dd852f2ac932563dedc1/_projects.json

      - name: "Creating .env file"
        run:
          echo "NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_NAME }}" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET_KEY }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_CLOUD_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_CLOUD_KEY }}" >> .env
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          include-hidden-files: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bap-dashboard/
            git pull
            npm install
            npm run build
            pm2 restart 0